{{ config(materialized='view') }}

select
    split(site, '-') [safe_offset(0)] app_name,
    customer_id,
    {{email_hash('email')}} email,
    --first_name,
    --last_name,
    --company company,
    --phone phone,
    --vat_number vat_number,
    --billing_address_line1 billing_address_line1,
    --billing_address_line2 billing_address_line2,
    --billing_address_city billing_address_city,
    --billing_address_state billing_address_state,
    billing_address_country country,
    --billing_address_zip billing_address_zip,
    auto_collection auto_collection,
    --offline_payment_method offline_payment_method,
    card_status card_status,
    safe.parse_datetime('%d-%b-%Y %H:%M', created_at) created_at,
    mparticleid mparticle_id,
    advertisingid advertising_id,
    split(site, '-') [safe_offset(1)] acc,
    --cid cid,
    --billing_address_state_code billing_address_state_code,
    customer_portal_status customer_portal_status,
    --net_term_days net_term_days,
    --taxability taxability,
    --locale locale,
    --billing_address_first_name billing_address_first_name,
    --billing_address_last_name billing_address_last_name,
    --billing_address_email billing_address_email,
    --billing_address_company billing_address_company,
    --billing_address_phone billing_address_phone,
    --billing_address_line3 billing_address_line3,
    --billing_address_validation_status billing_address_validation_status,
    --is_location_valid is_location_valid,
    --vat_number_status vat_number_status,
    --vat_number_validated_time vat_number_validated_time,
    --vat_number_prefix vat_number_prefix,
    --parent parent,
    --payment_owner payment_owner,
    --auto_close_invoice auto_close_invoice,
    load_ts,
    update_ts
from {{ source('staging', 'chargebee_customers') }}